#!/bin/bash

# This is script automates the deployments of KodeKloud e-commerce app



#######################################
# Function to highlight if the installation and verification has an error or passed
# Arguments:
#   COLOR.  green, red
#######################################
function print_color(){
    
    case $1 in
        "green") COLOR='\033[0;32m'
        ;;
        "red") COLOR='\033[0;31m'
        ;;
        "*") NO_COLOR='\033[0m'
    esac    
  
    echo -e "${COLOR} $2 ${NO_COLOR}"
}


#######################################
# Function to check services status 
# Arguments:
#   Service.    httpd, firewalld, mariadb
#######################################
function check_service(){

    is_service_active=$(systemctl is-active $1)

    if [ $is_service_active = "active" ]
    then
        print_color "green" "$1 Service is active"
    else
        print_color "red"    "$1 Service is not active"
        exit 1 
    fi 

}


#######################################
# Function to check firewalld rule ports are rigth configured
# Arguments:
#   Ports.    3306, 80
#######################################
function is_firewalld_rule_configured(){
    
    firewalld_ports=$(sudo firewall-cmd --list-all --zone=public | grep ports)

    if [[ $firewalld_ports = *$1* ]]
    then
        print_color "green" "Port $1 is configured"
    else
        print_color "red" "Port $1 is not configured"   
        exit 1
    fi
}


#######################################
# Function to check is the items are present in the web page
# Arguments:
#   Webpage
#   Items.    Laptop, VR, Watch
#######################################
function check_item(){

    web_page=$(curl http://localhost)

    if [[ $1 = *$2* ]]
    then
        print_color "green" "$2 is present in the webpage"
    else
        print_color "red" "$2 is not present in the webpage"  
        exit 1
    fi
}

# Install FirewallD
print_color "green" "Install FirewallD"
sudo yum install -y firewalld
sudo service firewalld start
sudo systemctl enable firewalld

# Check if the FirewallD is activated

check_service firewalld


# Install MariaDB
print_color "green"  "Installing MariaDB..."
sudo yum install -y mariadb-server
sudo service mariadb start
sudo systemctl enable mariadb

# Check if the MariaDB is installed/activated

check_service mariadb

# Configure firewall for Database
print_color "green"  "Adding firewall rules for DB ..."
sudo firewall-cmd --permanent --zone=public --add-port=3306/tcp
sudo firewall-cmd --reload

# Check the ports are correct

is_firewalld_rule_configured 3306


# Configure Database 
print_color "green"  "Configure DB..."
cat > configure-db.sql <<-EOF
CREATE DATABASE ecomdb;
CREATE USER 'ecomuser'@'localhost' IDENTIFIED BY 'ecompassword';
GRANT ALL PRIVILEGES ON *.* TO 'ecomuser'@'localhost';
FLUSH PRIVILEGES;
EOF

sudo mysql  < configure-db.sql

# Configure Database - Create data for database
print_color "green"  "Loading data into DB..."
cat > db-load-script.sql <<-EOF
USE ecomdb;
CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;

INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");

EOF

sudo mysql < db-load-script.sql

# Check the tables are made
 
 mysqldb_results=$(sudo mysql -e "use ecomdb; select * from products;")

 if [[ $mysqldb_results = *Laptop* ]]
 then
    print_color "green" "Inventory data loaded"
else
    print_color "red" "Inventory data not loaded"    
    exit 1
fi


###Deploy and Configure Web####


#Install required packages and configure Firewall rules
print_color "green"  "Configure Web Server and Firewall..."
sudo yum install -y httpd php php-mysql
sudo firewall-cmd --permanent --zone=public --add-port=80/tcp
sudo firewall-cmd --reload


# Check the ports are correct

is_firewalld_rule_configured 80

#Configure httpd
sudo sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf

#Start httpd
print_color "green"  "Starting Web Server..."
sudo service httpd start
sudo systemctl enable httpd

check_service httpd

#Download code and GIT
print_color "green"  "Cloning GIT Repo..."
sudo yum install -y git
sudo git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/


# Update index.php
# Update index.php file to connect to the right database server. 
# In this case localhost since the database is on the same server of the webserver

sudo sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php


print_color "green"  "All set."


#Test

web_page=$(curl http://localhost)

for item in Laptop Drone VR Watch
    do 
        check_item "$web_page" $item
    done    
